#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "ÀÏµ¶°Ñ×Ó",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÇàÄ¾½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÖñóÒ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "»ÒÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "óïÍõËï",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIM "Ìì²ÏË¿´ø" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIW "°×»¢Ö®îø" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIC "ÇàÁú±¦¼×" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIR "÷ÈÓ°ÉñÑ¥" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "À¶Ìì´¸",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":               HIG "»ÙÌì´¸" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":               BLU "À¶²¼ÒÂ" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÛòÏÂµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÌúÉÙ",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÓÝ¼§½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "Ñ©Èï¶ù",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "´Ö²¼°×ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "´Ö²¼¶ì»ÆÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "¶¡³Ë·ç",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÆßÐÇ·­ÔÆÑ¥",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÈýÇåÉñ¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÌìÊ¦µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "Öä½£Íõ·ò",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "è·½£Íõ·ò",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "¾ÅÐÇ·­ÔÆÑ¥",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "Áù¸ùÇå¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "µØÆìµÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÕË·¿ÏÈÉú",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÉÏ¹Ù½ðºç",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÎâÇà",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "½ðÇ®ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "Áú·ïË«»·",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "°¢·É",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                 HIR "°ó×ÅÒ»¿éÄ¾Í·µÄÐâÌúÆ¬" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "Î÷ÃÅ´µÑ©",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                 HIR "º®Ìì´µÑª" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                 "º®Ìì±ùÒÂ" ,
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÂúÁ³·çËªµÄÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "Â½Ð¡·ï",
                "quest_type":           "É±",
                "exp_bonus":            100,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

