#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "Ð¡¾ê",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÆÆÀÃµÄ·Ûºì²¼ÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "À¶ÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÆßÐÇ´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ô°¹¤",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "³¤¼ô",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ð¡Ñò¸á",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÐíÁ®Áú",
                "quest_type":           "É±",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "»Ò²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Çà·æ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÂÌ¶¹Ãç",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Íã¶¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Çà¶¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "¾Â²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "´ó°×²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "´óÇà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ð¡Çà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Ð¡°×²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "°×ÓñÐ¡ÂíÍ°",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Âí××Ä¾Ë¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "ÃÛ·ä",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "»Æ½ð",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÆòØ¤",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "·è¹·",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¾ÉÊé",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÉáÀû×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "»¤ËÂ²ØÄá",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ò»»·ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Òõ¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ñô¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÍÕ±³ÀÏºº",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "²ÝÐ¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ËòÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "µÇÍ½×Ó",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Öñ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÅÙ»¨ÓÍ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÓÍÓÍµÄÖ½",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "¼¦Èâ°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ñ¼ÓÍ°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ºìÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÂÌÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "»ÆÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°×É«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ºÚÉ«µÄÏ¸Õë",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "³¯°ÝµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "É¨µØµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÉÕ·¹µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÌôË®µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¿³²ñµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÌÔÃ×µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "´òÔÓµÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Äî¾­µÄºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "´Ö²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÃÞ²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "À¶²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ï´µÃ·¢°×µÄÉ®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Çà²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "×Ï²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ºÚ²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°×²¼É®Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "´Ö²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÃÞ²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "À¶²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ï´µÃ·¢°×µÄÉ®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Çà²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "×Ï²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ºÚ²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°×²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "·ç¾²",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ë®ÊÖ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "»¨½³",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÀÏºº",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÕÔ¹úÌ©",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ô°¹¤¼ô",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡Ô°¹¤",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÀÏÅ©",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Á­µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÀÏÕß",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÑÌ¶·",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "³ÁÏãÕòµÄµØÍ·Éß",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÌôÉ½·ò",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´ÖÄ¾±âµ£",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "âã»ÚÍ½",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÑÅ·¼",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»ï¼Æ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ºÚÉ«¾¢×°",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÂãÌåÅ®ÈË",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "·çÉ§ÑÅÈË",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÄêÇàÈË",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "É¥¾¡ÌìÁ¼µÄÐóÉú",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ñ¾»·",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "²ÊÈ¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡¶µ¶µ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡Î÷ÃÅ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Å®Ó¶ÈË",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "ÇàÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Áù½Ç´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "¼¦Ã«",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "²É»¨æ¤",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "×Ï»¨°ê¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "×ÏÒÂ¼Ò¶¡",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "°ËÀãÐþÌú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "öÇÓãºâ±ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "¹ýÕÐÒªÖ¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            50,
        ]),
        ([      "quest":                "´ó±è×Ó¹ÃÄï",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "µÇÉ½Õß",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "²ÉÁâÅ®",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "±Ú»¢",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
        ([      "quest":                "Ð¡Ã¨ßä",
                "quest_type":           "É±",
                "exp_bonus":            20,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

