#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "×Ï»¨°ê¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Óü×ä",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "¶Û½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "»¤Ôº",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ð¡¶Ì½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ð¡ÃàÑò",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Öª¿ÍµÀÈË",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "»ÆÉ«µÀ¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Çà²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Åí³¤¾»",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ÎäÁÖÐ¡ºÀ½Ü",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ãçµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ó­¿ÍÉ®",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ÔÆÓÎÉ®ÈË",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "¼«ÀÖåÐÒ£É¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "»¯Ê¬·Û",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ò¹ÐÐÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "¾«¸Ö·Éµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ºì×ìÐ¡ÂéÈ¸",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "ÀÏÎÝÈË",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "öùÓã",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "Ë®Éß",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),
        ([      "quest":                "½ðË¿È¸",
                "quest_type":           "É±",
                "exp_bonus":            30,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

