#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "´¾ÓÚ»³Ì«",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÉßÁÛÆ¤±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Ò¶Áé",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ºìÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Ò¶Ñ©",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "¹·ÀÉ¾ý",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "»ÆÒÂÈË",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Ð¡À¼",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "¶¾ÁúÉ³",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Äµµ¤",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "¶¬Çà",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Ãµ¹å",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "¶Å¾é",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "°×ÅÛ¸¾",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Àî³¤É÷",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "»Ò²¼µÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "¹©Ïã",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Ì«¼«È­Á·¹¦Í¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÂäµÚÊéÉú",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "×¥ÆÆÃÀÈËÁ³",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "°×¾±»ÒÐÜ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "Îý»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "²éÃÍ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "»ÆÒÂÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "½ðÇ®ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "·¼¶ù",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":               HIY "Îå" + HIR "²Ê" NOR + "½ôÉíÈ¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "´óºú×Ó",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÀÏÊµºÍÉÐ",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "¿ñæÎ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÍÅ½ð¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "´óºú×ÓºÀ¿Í",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÀîÉñÍ¯",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),
        ([      "quest":                "ÀÏÉ½Ñò",
                "quest_type":           "É±",
                "exp_bonus":            40,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

