#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "½«¾ü",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "±í¸ç",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÎèÁø½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ºìÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "¹ËÔÆ·ÉµÄÃØº¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Ò¶¹Âºè",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "°×½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "·ÛÑà×Ó",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Í­Ç®ïÚ",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Æ¤ÄÒ",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "¡¸Èý²Å½£Æ×¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "Õ¼²·ÈëÃÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÌúºÐ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "¹ÖÊÞ",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "°×¶îÃÍ»¢",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "·½Óñ·É",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÀäÈôËª",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Òø»¨Çàµ×Åû¼çÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Òø»¨Çàµ×Åû¼çÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "À¶ºú×Ó",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "´óÅ£",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Ï¹×Ó",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "·çÔÆÑÃÒÛ",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "É±Íþ°ô",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "·çÔÆ²î·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "ÂãÌåÄÐÈË",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "Ã½ÆÅ",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),
        ([      "quest":                "¹êÅ«",
                "quest_type":           "É±",
                "exp_bonus":            60,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

