#include <ansi.h>
mapping *quest = ({
        ([      "quest":                "ÈËÆ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¿¾É½ÖíÈâ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´óÀÏÊó",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÂìÒÏ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "òÐòÐ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "³¤½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÐÅ¸ë",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ºÚÄµµ¤",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "À¶Ìì¶ì",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "×ÏÂÞÀ¼",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ºìÃ¶¹å",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "°×²è»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»ÆÃµ¹å",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¹Â¶ÀÃÀ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¹ÅÐÎ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Í­ÉÚ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ñà×Ó",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»¨ºûµû",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÎÚÌúìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ä¾ìøÕÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÆÆ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÆÆÍäµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÉáÀû×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Óñ½äÖ¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¿¾ÑòÍÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÉßÒ©",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÑòÆ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¶ñÄ§Íö»ê",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":               HIC "¹íÑÀÐþÚ¤ÕÈ" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "±ùÐÄ¾÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Íü»ê»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":               HIG "Íü»ê¹û" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¾ÅÌõ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¾ÅÍò",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¾ÅÍ°",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "×ÏÝ¼ÓñÈØ¸à",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":               HIR "¶Ï³¦²Ý" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "×Ï½ðºùÂ«",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "²ÐÆÆ¹Å»­",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":               CYN "±ªÑÀÊÖ»·" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "´óÏä×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":               "Ñ©¸òó¡" ,
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "²ØÏã",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":               "²è×©" ,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":               "ºúµ¶" ,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÓñÖé»¨" ,
                "quest_type":           "Ñ°",
                "exp_bonus":            25,
        ]),
        ([      "quest":                "Óñ½äÖ¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":               "ÓñÊÖïí" ,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                 "ÂéÈ¸" ,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                 "ËÉÊó" ,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÀÏ¸¾ÈË",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "·¹Àº",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        
        ([      "quest":                "Öñ¿ê×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´ÖÃ×·¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ìú½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¿³²ñ¸«",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Öñ¿ð",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "·¹Àº",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        
        ([      "quest":                "ÌúºÐ",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "³úÍ·",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¶¤îÙ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´óÌú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Á­µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸Èý²Å½£Æ×¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÂôÃæµÄÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÄÏ¹¬Ê®Èý",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÖÐÒ©µêÀÏ°å",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "±±ÜÎ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Á­µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¿³ÁÖµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "²ÚÃæ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "µ³²Î",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»´É½",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÏÊÓã",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¾Â²ËºÏ×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¼¦Ã«ë¦×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¿ªñÉ¿ã",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "µ±¹é",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ºÚ´ÉÒ©ÎÍ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ð¡Ãæ¹ÝµÄµØÆõ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "¹ÅÓñÅÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÂÞÉ²ÅÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            100,
        ]),
        ([      "quest":                "ÉÏ²èµÄµÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "É¨µØµÄµÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÉÕ·¹µÄµÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÌôË®µÄµÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¿³²ñµÄµÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÌÔÃ×µÄµÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡Öñ·÷³¾",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´¿½ðÒ¶×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "ÃæÄ¿¿Õ°×µÄÄ¾Ïñ",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "²è»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¾Å½Ø±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´óó¯òë",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ËØ²Ë°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Éú¼å°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡Áý°ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´óÇà²Ë",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "µ¥µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»ðÅÚÍè",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "ºÚÄµµ¤" ,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":               "¡¸¼ÎµÂÎÄÑ¡¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸¾Åèº¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸Ì«¹«±ç¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸Áº¸¸ÎÄ¼¯¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸ËµÂÉ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸¹ÅÎÄÖ¾¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸ÏçÊé¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¡¸Ù«·çÕ«Ê«¼¯¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÄÚ¹¦ÐÄ·¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "·ûÖäÈëÃÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Çá¹¦ÈëÃÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ä§·¨¼ò½é",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÓñÆÑÍÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "½ðÆ¿Ã·",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Çà´É´óÍë",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´àÆ¤²ÝÓã",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "³ÂÆ¤´óÏº",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´¨Î¶¸ÎÆ¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¹·Æ¤¸àÒ©",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "×ÓÄ¸Ë«»·",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ü½ÈØ÷­Æ¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»¢¹ÇÍè",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¸ßÀöÏã½¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "éÏé­Óã³á",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¹ûÖ­ÓãÇò",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»¨·Û´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»õÆ±",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ºìÓÍ¼¦Æ¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Óñô¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Óñ»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÓñÖ¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Óñïí",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "½õÐåÓãË¿",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "½·ÑÎÃæ½î",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÔÆÄÏ°×Ò©",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "É±ÊÖÅÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                HIR "É±ÊÖ½£" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "·Éµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Â±Î¶¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÄàÈË¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ºúÂÜ²·",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Å£Í·",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´ó¾Æ´ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÈËÆ¤Ãæ¾ß",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "·çÔÆÔÞ¸è",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÖåÖåµÄÆÆÖ½Æ¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ò»Î¶ÓãÃ×",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Çå³´÷­ºý",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Çå³´ÏºÈÊ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÖóÊìÁËµÄÇù",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÈéÏãöðÓã",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ã©É½µÀÊõÈëÃÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´ó·çÍè",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Å£Æ¤¶Ü",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÉúÉÕÇàÓã",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÉúÉÕ°Ç³á",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "°×Ã«½í",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡·ç³µ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡³´·ÛË¿",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÂÞ²·Ìõ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÑòÍ·",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Òø³²ºìÖé",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´óºÚÊ¯",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "·çÇå",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡½ð¸Õ¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´ó½ð¸Õ¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Äù°ã¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´ó³Ë¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡³Ë¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Í­·ðÖÓ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Í­·ð¹Ä",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¹ÅËÉÇÙ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Æß²ÊË¿¶Ð´ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "»ð¾ÞÁé",
                "quest_type":           "É±",
                "exp_bonus":            45,
        ]),
        ([      "quest":                HIR "»ðÑæ³¤µ¶" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            65,
        ]),
        ([      "quest":                "Ó©»ð³æ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ºÚÓñ·¢ô¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´óÑã",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÎðÍüÎÒ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÕÑºì",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Èíºì",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ê¯ÁñÈ¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "²·ÑÇÄÐ",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Á¼¼Ò¸¾Å®",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´øÑªÉ´ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "²ÐÆÆµÄÅ®×ÓÄÚÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¼ÒÅ«",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¼ÒÅ«¶Ì¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "²ÝÓñèµ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¹ÅÓñÅÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            95,
        ]),
        ([      "quest":                "Ð¡½ð±­",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¾ÆÓñèµ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÁøÓñèµ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Å®Óñèµ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÄÛÅº",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ë®Óñèµ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ñ©Óñèµ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÄÛÅº",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´óÃÞ°À",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÀîÏ¼",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Â±µ°",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÂÞÉ²ÅÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            95,
        ]),
        ([      "quest":                "Â¹È×",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¾«¸ÖÔ°Í°",
                "quest_type":           "Ñ°",
                "exp_bonus":            95,
        ]),
        ([      "quest":                "Ò°ÈË²Î",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ñª³¦",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÐþËÕ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ë¿³ñÂí¹Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´µÑ©²ÐÔÆ½í",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´µÑ©²ÐÔÆÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´µÑ©²ÐÔÆÑ¥",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "´µÑ©²ÐÔÆ´ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ã·Ä¾³¤µÊ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÂéÉþ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¸ÉÄ¾²ñ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "°ë¸ÉµÄÑªµÎ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ð¡Ä¾·¤",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Â·±ßµÄÒ°»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "¿Ý»ÆµÄÒ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "Ã·Ê÷Ó×Ãç",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "°ë¸ÉµÄÄ¾²ñ",
                "quest_type":           "Ñ°",
                "exp_bonus":            15,
        ]),
        ([      "quest":                "ÈËÓ°",
                "quest_type":           "É±",
                "exp_bonus":            15,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

