#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "Öé±¦ÉÌ",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "±ÌÓñºúµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "ÔÆ×ä",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "·ç±ø",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "·çÔÆÕ½¼×",
                "quest_type":           "Ñ°",
                "exp_bonus":            75,
        ]),
        ([      "quest":                HIR "ºìÓ§" NOR + "³¤Ç¹" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "¾£ÎÞÃü",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "²Î»ú´óÊ¦",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "ÁÒ»ðÄõÁú",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "¾µ»ê",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "ÌìÈ±¹ÅÔÂº®",
                "quest_type":           "Ñ°",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "ÐØ½ó°ë¿ªµÄÇáÉ´Ë¿ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "¼§±ùÑã",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "À¶Ð¡ÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "½¦ÂúÑªµÄºÚ²¼ÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "Öî¸ðÊ®Ò»",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "Ð¡¶¹¶¹",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "¹ÜÁã",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "ÕÅ½£",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),
        ([      "quest":                "òðÍõ",
                "quest_type":           "É±",
                "exp_bonus":            75,
        ]),


});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

