#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "ÊÕÆÆÀÃµÄ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "éÔ·ò",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ìú¸«",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÆòØ¤",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¾ÉÊé",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "½ð¼¦¼¦",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ïº",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Óã",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "»¤ÐÄ¾µ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":               HIC "ÎÞÓ°ÉñÕë" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ò°Ñ¼",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "À×»ðÖé",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÏìÎ²Éß",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Óñ·¢ô¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Öñµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Öñ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÈýÇåµÀÊõ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¡¸Çá¹¦ÈëÃÅ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¡¸ÄÚ¹¦¼ò½é¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¡¸È­·¨ÈëÃÅ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¡¸½£Êõ¼ò½é¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¡¸²ðÕÐÃØ¾ö¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¡¸ÉÁ¶ãÖ®Êõ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¡¸È­·¨ÈëÃÅ¡¹",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Æ¤±Þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ä¾¹÷",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "µ¥µ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ìú´¸",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÍÕ±³ÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ä¥²Ëµ¶µÄ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "´©¿ªñÉ¿ãµÄÐ¡º¢¶ù",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÂôÓãµÄ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÂòÓãµÄÐ¡¹ÃÄï",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Å©¼ÒÅ®",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "¼¦Ã«ë¦×Ó",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Å©·ò",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Å©¾ßµêÀÏ°å",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "°¢·¢",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ºúÓ¢",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÀÏ²Ã·ì",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÍÁæ½",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Âô²ËµÄ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "´óÅÖ×Ó",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÂôÍæ¾ßµÄ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÂôÒ©µÄ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÍõÈÊµÂ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "µêÐ¡¶þ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÀÏ°åÄï",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÕÅÌú½³",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÉÏÁËÄê¼ÍµÄÀÏÌ«ÆÅ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "²è²©Ê¿",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÁúÐ¡ÔÆ",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÓÍÀ±ÖíÅÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÓãÏãÈâË¿",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ö½»¨",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ö½Ç®",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÖíÍ·",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "½·ÑÎÅÅ¹Ç",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Ç§½ðÐ¡½ã",
                "quest_type":           "É±",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "Òøô¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),
        ([      "quest":                "ÇáÂÞ³ñÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            10,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

