#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "³ø×Ó",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "±ÌÓñµ¶",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "»¤ËÂ²ØÄá",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "´óºìÄáÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "´óÃàÑò",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÍÕ±³ÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ð¡´ä",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "Ðå»¨Ð¬",
                "quest_type":           "Ñ°",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "·ÛºìÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ï¸Ã·½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "µÀÊ¿",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ËïÌìÃð",
                "quest_type":           "É±",
                "exp_bonus":            55,
        ]),
        ([      "quest":                "Ð»³¤ÇÚ",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ËÎ³¤Çå",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "½ð»¤ÎÀ",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "´ó³ø",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Â±Î¶¶ù",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÑÅ¹«×Ó",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ß¡ÉÈ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "ÇÎð±Ä¸",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Îèµû²ÊÉÀ",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "¹Ø¶«´óºº",
                "quest_type":           "É±",
                "exp_bonus":            35,
        ]),
        ([      "quest":                "Ñª³¦",
                "quest_type":           "Ñ°",
                "exp_bonus":            35,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

